# Generated by Django 5.1.3 on 2024-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user_name', max_length=100),
        ),
    ]
