---
apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
  namespace: etl-express-project
spec:
  selector:
    app: user-manager
  ports:
    - protocol: TCP
      name: "user-manager"
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: "script-manager"
      port: 8001
      targetPort: 8001
    - protocol: TCP
      name: "etl-task-manager"
      port: 8002
      targetPort: 8002
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: etl-express-project
  annotations:
     kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - 
      http:
        paths:
          - path: /etl-express-project/user_manager
            pathType: Prefix
            backend:
              service:
                name: user-manager-service
                port:
                  number: 8000
    - 
      http:
        paths:
          - path: /etl-express-project/scripts_manager
            pathType: Prefix
            backend:
              service:
                name: user-manager-service
                port:
                  number: 8001
    - 
      http:
        paths:
          - path: /etl-express-project/etl_task_manager
            pathType: Prefix
            backend:
              service:
                name: user-manager-service
                port:
                  number: 8002


      
