apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  selector:
    app: user-manager
  ports:
    - protocol: TCP
      name: "user-manager"
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: "script-manager"
      port: 8001
      targetPort: 8001
  type: LoadBalancer
