# Generated by Django 5.1.4 on 2024-12-23 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTask',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('released', models.BooleanField(default=False)),
                ('extraction_script', models.TextField(blank=True, null=True)),
                ('field_rules', models.JSONField(blank=True, default=list)),
                ('anonymization_rules', models.JSONField(blank=True, default=list)),
                ('transformation_scripts', models.JSONField(blank=True, default=list)),
                ('uploading_script', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused'), ('Stopped', 'Stopped')], default='Running', max_length=20)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extracted_data_count', models.BigIntegerField(default=0)),
                ('etl_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.etltask')),
            ],
        ),
    ]
