# Generated by Django 5.1.3 on 2024-12-01 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_datamodule_id', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255)),
                ('released', models.BooleanField(default=False)),
                ('script_type', models.CharField(choices=[('extractor', 'Extractor'), ('field_rule', 'Field Rule'), ('anonymization_rule', 'Anonymization Rule'), ('transformer', 'Transformation Script'), ('uploader', 'Uploader')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('Integer', 'Integer'), ('String', 'String'), ('Double', 'Double')], max_length=50)),
                ('type', models.CharField(choices=[('FillEmpty', 'Fill Empty'), ('IgnoreEmpty', 'Ignore Empty'), ('RemoveEmpty', 'Remove Empty'), ('FillOutOfRange', 'Fill Out of Range'), ('IgnoreOutOfRange', 'Ignore Out of Range'), ('RemoveOutOfRange', 'Remove Out of Range')], max_length=50)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_rule', to='api.script')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Generalization', 'Generalization'), ('Suppression', 'Suppression'), ('Anatomization', 'Anatomization'), ('Permutation', 'Permutation'), ('Perturbation', 'Perturbation')], max_length=50)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_rule', to='api.script')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_script', models.TextField()),
                ('type', models.CharField(choices=[('Merge', 'Merge'), ('Update', 'Update')], max_length=50)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_script', to='api.script')),
            ],
        ),
    ]
