# Generated by Django 5.1.3 on 2024-12-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.script'),
        ),
        migrations.AlterField(
            model_name='anonymizationrule',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_rule', to='api.script'),
        ),
        migrations.AlterField(
            model_name='fieldrule',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rule', to='api.script'),
        ),
        migrations.AlterField(
            model_name='transformationscript',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformation_script', to='api.script'),
        ),
    ]
